title: "Olanrewaju Oyebanji"
description: "Data Analyst | Educator | Life-Long Learner"
logo: "/assets/img/Avatar.png"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: "Olanrewaju Oyebanji"
  avatar: "/assets/img/Avatar.png"
  bio: "Data Analyst | Educator | Life-Long Learner"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lanre-oye"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lanreoye"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: double
      toc: true
      toc_sticky: true
