title: "Olanrewaju Oyebanji"
description: "Data Analyst | Educator | Life-Long Learner"
logo:https://github.com/lanre-oye/Portfolio/blob/87263f91aebcfd4595a30e21f96dc8b9da8b0dd5/assets/img/avatar.png.png

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: "Olanrewaju Oyebanji"
  avatar:https://github.com/lanre-oye/Portfolio/blob/87263f91aebcfd4595a30e21f96dc8b9da8b0dd5/assets/img/avatar.png.png
  bio: "Data Analyst | Educator | Life-Long Learner"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/lanre-oye"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lanreoye"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: double
      toc: true
      toc_sticky: true
